
spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    url: jdbc:postgresql://localhost:5432/user_mgm
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}

springdoc:
  api-docs:
    groups:
      enabled: true